### ISSUE TITLE
Bug no controllers/home.js

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [rogertti/curso_nodejs#1]
Roger tudo bem? 

O bug esta em controllers/home.js nessa linha:

``` javascript
module.exports = function(app) {
    var HomeController = {
        index: function(req, res) {
            res.render('home/index');
        },
        login: function(req, res) {
            var nome = req.body.usuario.nome;
            var email = req.body.usuario.senha; // aqui tem que ser email...
            
                if(nome && email) {
                    var usuario = req.body.usuario;
                    usuario['contatos'] = [];
                    req.session.usuario = usuario;
                    res.redirect('/contatos');
                }
                else {
                    res.redirect('/');
                }
        },
        logout: function(req, res) {
            req.session.destroy();
            res.redirect('/');
        }
    };
        
    return HomeController;
};
``
`

**Comment by rogertti** [comment]
Certo Caio.

Corrigi o bug e agora redireciona para '/contatos', mas aparece o seguinte erro:

TypeError: Cannot read property 'usuario' of undefined

Instalei os módulos segundo o livro, mas mesmo assim aparece essa mensagem, lista dos módulos:

├─┬ body-parser@1.11.0
│ ├── bytes@1.0.0
│ ├── depd@1.0.0
│ ├── iconv-lite@0.4.6
│ ├── media-typer@0.3.0
│ ├─┬ on-finished@2.2.0
│ │ └── ee-first@1.1.0
│ ├── qs@2.3.3
│ ├─┬ raw-body@1.3.2
│ │ └── iconv-lite@0.4.6
│ └─┬ type-is@1.5.6
│   └─┬ mime-types@2.0.8
│     └── mime-db@1.6.1
├─┬ cookie-parser@1.3.3
│ ├── cookie@0.1.2
│ └── cookie-signature@1.0.5
├─┬ debug@2.1.1
│ └── ms@0.6.2
├── ejs@2.2.4
├─┬ express@5.0.0-alpha.1
│ ├─┬ accepts@1.1.4
│ │ ├─┬ mime-types@2.0.8
│ │ │ └── mime-db@1.6.1
│ │ └── negotiator@0.4.9
│ ├── content-disposition@0.5.0
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.5
│ ├── depd@1.0.0
│ ├── escape-html@1.0.1
│ ├─┬ etag@1.5.1
│ │ └── crc@3.2.1
│ ├── finalhandler@0.3.2
│ ├── fresh@0.2.4
│ ├── media-typer@0.3.0
│ ├── merge-descriptors@0.0.2
│ ├── methods@1.1.0
│ ├─┬ on-finished@2.1.1
│ │ └── ee-first@1.1.0
│ ├── parseurl@1.3.0
│ ├── path-to-regexp@0.1.3
│ ├─┬ proxy-addr@1.0.6
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@0.1.8
│ ├── qs@2.3.2
│ ├── range-parser@1.0.2
│ ├─┬ send@0.10.1
│ │ ├── destroy@1.0.3
│ │ ├── mime@1.2.11
│ │ └── ms@0.6.2
│ ├── serve-static@1.7.2
│ ├─┬ type-is@1.5.6
│ │ └─┬ mime-types@2.0.8
│ │   └── mime-db@1.6.1
│ ├── utils-merge@1.0.0
│ └── vary@1.0.0
├─┬ express-load@1.1.14
│ └── async@0.2.9
├─┬ express-session@1.10.2
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.5
│ ├── crc@3.2.1
│ ├── depd@1.0.0
│ ├── on-headers@1.0.0
│ ├── parseurl@1.3.0
│ ├─┬ uid-safe@1.0.3
│ │ ├── base64-url@1.2.0
│ │ └── native-or-bluebird@1.1.2
│ └── utils-merge@1.0.0
├─┬ morgan@1.5.1
│ ├── basic-auth@1.0.0
│ ├── depd@1.0.0
│ └─┬ on-finished@2.2.0
│   └── ee-first@1.1.0
└─┬ serve-favicon@2.2.0
  ├─┬ etag@1.5.1
  │ └── crc@3.2.1
  ├── fresh@0.2.4
  ├── ms@0.7.0
  └── parseurl@1.3.0

**Comment by caio-ribeiro-pereira** [comment]
Em controllers/contato.js vc inverteu a ordem dos parametros da função contatos.index, veja:

``` javascript
module.exports = function(app) {
    var ContatosController = {
        index: function(req, res) { // no seu código vc deixou res, req, o correto é req, res
            var usuario = req.session.usuario;
            var params = {usuario: usuario};
            res.render('contatos/index', params);
        }
    };
    
    return ContatosController;
};
```
